apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: south-ippool
spec:
  cidr: 10.0.0.0/8
  ipipMode: Always
  natOutgoing: true
  nodeSelector: zone == "south"
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: north-ippool
spec:
  cidr: 172.16.0.0/26
  ipipMode: Always
  natOutgoing: true
  nodeSelector: zone == "north"