apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab2-frontend-deployment
  labels:
    app: lab2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab2
  template:
    metadata:
      labels:
        app: lab2
    spec:
      containers:
        - name: lab2-frontend-pod
          image: ifilyaninitmo/itdt-contained-frontend:master
          env:
            - name: REACT_APP_USERNAME
              value: "Vladislav Korolev"
            - name: REACT_APP_COMPANY_NAME
              value: "VKOR_COMPANY"
          ports:
            - containerPort: 3000